# Generated by Django 5.1.6 on 2025-03-24 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("career", "0003_alter_career_level_alter_career_principal_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="level",
            options={"verbose_name": "Nivele"},
        ),
    ]
